
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author garci
 */
public class MULTITAREA extends javax.swing.JFrame {

    /**
     * Creates new form MULTITAREA
     */
    private boolean cerrar;

    public MULTITAREA() {
        initComponents();
        cerrar = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTrabar = new javax.swing.JButton();
        btnDivercion = new javax.swing.JButton();
        btnDestrabar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnTrabar.setText("Trabar Programa");
        btnTrabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrabarMouseClicked(evt);
            }
        });

        btnDivercion.setText("POR DIVERCION");
        btnDivercion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivercionMouseClicked(evt);
            }
        });
        btnDivercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivercionActionPerformed(evt);
            }
        });

        btnDestrabar.setText("Cerrar");
        btnDestrabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDestrabarMouseClicked(evt);
            }
        });
        btnDestrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnTrabar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnDivercion)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDestrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDivercion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDestrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabarMouseClicked
        Runnable runnable = new Runnable() {
            @Override
            public void run() { //AQUI VA LA TAREA QUE SE EJECUTA EN UN HILO, EN SEGUNDO PLANO.
                while (true) {
                    try {
                        Thread.sleep(1);
                        System.out.println(".");
                       
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MULTITAREA.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (cerrar) {
                        System.out.println("Termina hilo de ejecucion");
                        break;
                    }
                }
            }
        };
        // runnable.run();// Esto no funciona
        Thread miHilo = new Thread(runnable);
        miHilo.start();
        System.out.println("Se crea un hilo");

    }//GEN-LAST:event_btnTrabarMouseClicked

    private void btnDivercionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivercionMouseClicked
        // TODO add your handling code here:
        System.out.println("El boton funciona");
        dispose();
    }//GEN-LAST:event_btnDivercionMouseClicked

    private void btnDestrabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDestrabarMouseClicked
        //dispose();
    }//GEN-LAST:event_btnDestrabarMouseClicked

    private void btnDestrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestrabarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDestrabarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //Sirve para advertnecias al usuario antes de cerrar la pantalla
        cerrar = true;
        System.out.println("Cerrado");
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        System.out.println("Finalizado");
        dispose();


    }//GEN-LAST:event_formWindowClosing

    private void btnDivercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivercionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDivercionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MULTITAREA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MULTITAREA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MULTITAREA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MULTITAREA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MULTITAREA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDestrabar;
    private javax.swing.JButton btnDivercion;
    private javax.swing.JButton btnTrabar;
    // End of variables declaration//GEN-END:variables
}
